version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        depends_on:
            - postgres
        volumes:
            - ./.env:/app/.env
            - ./src:/app/src
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        env_file:
            - ./.env